# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: true
  tag_update: true
  rem_unregistered: false
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  share_limits: true
  skip_qb_version_check: true
  skip_cleanup: false

qbt:
  host: ghost-direct.usbx.me:13241
  user: CHANGEME
  pass: CHANGEME

settings:
  force_auto_tmm: true # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: tracker_error # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: noHL # Will set the tag of any torrents with no hardlinks.
  share_limits_tag: ~share_limit # Will add this tag when applying share limits to provide an easy way to filter torrents by share limit group/priority for each torrent
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has at least one or more of the tags defined here. Otherwise torrents will not be t$
  - noHL
  - tracker_error
  - cross-seed

directory:
  cross_seed:
  root_dir: /home/siffreinsg/downloads/qbittorrent
  remote_dir: /home/siffreinsg/downloads/qbittorrent
  recycle_bin: /home/siffreinsg/downloads/qbittorrent/.RecycleBin
  torrents_dir: /home/siffreinsg/.local/share/qBittorrent/BT_backup
  orphaned_dir: /home/siffreinsg/downloads/qbittorrent/orphaned_data

cat:
  radarr: /home/siffreinsg/downloads/qbittorrent/radarr
  radarr-sqp: /home/siffreinsg/downloads/qbittorrent/radarr-sqp
  sonarr: /home/siffreinsg/downloads/qbittorrent/sonarr
  prowlarr: /home/siffreinsg/downloads/qbittorrent/prowlarr
  qbittorrent: /home/siffreinsg/downloads/qbittorrent/

cat_change:

tracker:
  joinpeers|drago-server:
    tag: yggtorrent
  other:
    tag: other

nohardlinks:
- radarr-completed
- radarr-sqp-completed
- sonarr-completed

share_limits:
  arr_noHL_private:
    priority: 1
    include_all_tags:
    - noHL
    include_any_tags:
    - yggtorrent
    categories:
    - radarr-completed
    - radarr-sqp-completed
    - sonarr-completed
    max_ratio: 1
    max_seeding_time: 4320 # 3 days
    cleanup: true
  arr_noHL_public:
    priority: 2
    include_all_tags:
    - noHL
    exclude_any_tags:
    - yggtorrent
    categories:
    - radarr-completed
    - radarr-sqp-completed
    - sonarr-completed
    max_ratio: 0
    max_seeding_time: 0
    cleanup: true
  manual_noHL_private:
    priority: 5
    include_all_tags:
    - noHL
    - qbittorrent
    include_any_tags:
    - yggtorrent
    max_ratio: 5.0
    max_seeding_time: 129600 # 90 days
    min_seeding_time: 43200 # 30 days
    cleanup: false
    min_num_seeds: 1
  manual_noHL_public:
    priority: 6
    include_all_tags:
    - noHL
    - qbittorrent
    exclude_any_tags:
    - yggtorrent
    max_ratio: 0
    max_seeding_time: 0
    limit_upload_speed: 0
    cleanup: false
  private:
    priority: 15
    include_any_tags:
    - yggtorrent
    categories:
    - radarr-completed
    - radarr-sqp-completed
    - sonarr-completed
    cleanup: true
    max_ratio: -1
    max_seeding_time: -1
    min_seeding_time: 129600 # 90 days
  public:
    priority: 20
    exclude_any_tags:
    - yggtorrent
    categories:
    - radarr-completed
    - radarr-sqp-completed
    - sonarr-completed
    max_ratio: 0
    max_seeding_time: 0
    limit_upload_speed: 0
    cleanup: true
  default:
    priority: 999
    max_ratio: 1
    max_seeding_time: 43200 # 30 days
    cleanup: false

recyclebin:
  enabled: true
  empty_after_x_days: 7
  save_torrents: true
  split_by_category: true

orphaned:
  empty_after_x_days: 60
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
  - '**/*_unpackerred'

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    share_limits:
    cleanup_dirs:
